server:
    port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: api-auth
                  uri: 'http://api-users:8888/'
                  predicates:
                      - Path=/api/users/**
                - id: api-courses
                  uri: 'http://api-courses:8889/'
                  predicates:
                      - Path=/api/courses/**
                - id: api-courses-mobile
                  uri: 'http://api-courses-mobile:3000/'
                  predicates:
                      - Path=/api/courses-mobile/**
            globalcors:
              cors-configurations:
                '[/**]':
                  allowedOrigins: "*"
                  allowedHeaders: "*"
                  allowedMethods:
                    - GET
                    - POST
                    - PUT
                    - PATCH
                    - DELETE