server:
    port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: api-auth
                  uri: 'http://localhost:8888/'
                  predicates:
                      - Path=/api/**
                      - Header=Authorization, \.*?
                - id: api-courses
                  uri: 'http://localhost:8889/'
                  predicates:
                      - Path=/api/courses/**
            globalcors:
              cors-configurations:
                '[/**]':
                  allowedOrigins: "*"
                  allowedHeaders: "*"
                  allowedMethods:
                    - GET
                    - POST
                    - PUT
                    - PATCH
                    - DELETE